# Unified Model Evaluation

Validates every registered **prediction** in a project against observed
deforestation, producing the standard *udef-arp* accuracy indices
(**wRMSE**, **MedAE**, **RMSE**, **R²**, in hectares) per `(model, period)`,
plus a side-by-side metric comparison.

This is the new-construction successor to `notebooks_legacy/6.models_evaluation.ipynb`.
Two things changed:

| Legacy | This notebook |
|--------|---------------|
| Filesystem globbing to discover risk maps + defrate CSVs | iterates `project.predictions` (each carries its `path`, `dataset_name`, `window`) |
| `far.validation_udef_arp` on a packed **`fcc123`** raster | native **two-explicit-layer** validation (binary `defor` + `forest`), the same convention `spatialrisk.rmj.deforrate` already uses — no `fcc123`, no `forestatrisk` |

**Per-period defrate** (each period's risk map paired with that period's own
deforestation-rate table) — matching the original
[deforisk-qgis-plugin](https://github.com/ghislainv/deforisk-qgis-plugin) and the
legacy notebook. The deforestation / forest-at-start layers for each prediction
are recovered from the prediction's **dataset** (`target` = deforestation,
`forest_gfc` feature = forest at period start), so nothing is hard-coded.

## 1. Setup

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# GDAL optimizations (block reads)
import multiprocessing as mp
import os

num_cores = max(1, mp.cpu_count() - 2)
os.environ["GDAL_NUM_THREADS"] = f"{num_cores}"
os.environ["GDAL_CACHEMAX"] = "1024"

In [3]:
import sys
import re
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from osgeo import gdal

sys.path.append("..")
from spatialrisk import Project, rmj
from spatialrisk.evaluation import (
    make_square, validate_two_layer, evaluate_predictions, interval_from_target, label_for,
)

/home/jserafini/micromamba/envs/spatial-risk/lib/python3.11/site-packages/dask/array/chunk_types.py:110: UserWarning:
--------------------------------------------------------------------------------

  CuPy may not function correctly because multiple CuPy packages are installed
  in your environment:

    cupy, cupy-cuda12x

  Follow these steps to resolve this issue:

    1. For all packages listed above, run the following command to remove all
       existing CuPy installations:

         $ pip uninstall <package_name>

      If you previously installed CuPy via conda, also run the following:

         $ conda uninstall cupy

    2. Install the appropriate CuPy package.
       Refer to the Installation Guide for detailed instructions.

         https://docs.cupy.dev/en/stable/install.html

--------------------------------------------------------------------------------

  import cupy

In [4]:
project_name = "mtq-refactor"
project = Project.load(project_name=project_name)

print("\nRegistered predictions:")
for k in project.list_predictions():
    print(" ", k)

Loaded 5 model(s)
✓ Target set: forest_loss_2015_2020 (static)
✓ Features set: 9 variables
  Static: altitude, protected_area, rivers_dist, roads_dist, slope, subj
  Temporal (year: 2015): forest_gfc, forest_gfc_edge, towns_dist
✓ Target set: forest_loss_2020_2024 (static)
✓ Features set: 9 variables
  Static: altitude, protected_area, rivers_dist, roads_dist, slope, subj
  Temporal (year: 2020): forest_gfc, forest_gfc_edge, towns_dist
Loaded 2 dataset(s)
Loaded 14 prediction(s)
Project loaded from: /home/jserafini/Desktop/projects/spatial_risk/spatial-risk-module/data/mtq-refactor/mtq-refactor_project.json
Loaded 23 processed variables

Registered predictions:
  glm_glm_v1__calibration_y2015
  glm_glm_v1__validation_y2015
  rf_rf_v1__calibration_y2015
  rf_rf_v1__validation_y2015
  icar_icar_v1__calibration_y2015
  icar_icar_v1__validation_y2015
  mw_calibration_mw__calibration_y2015_w5
  mw_calibration_mw__calibration_y2015_w11
  mw_calibration_mw__calibration_y2015_w21
  mw_calibration_mw__validation_y2015_w5
  mw_calibration_mw__validation_y2015_w11
  mw_calibration_mw__validation_y2015_w21
  jnr_calibration_jnr__calibration_y2015
  jnr_calibration_jnr__validation_y2015

## 2. Native two-layer validation

`validate_two_layer` is a faithful port of `forestatrisk.validation_udef_arp`.
The **only** change: the observed per-cell forest/deforestation counts come from
two explicit binary layers instead of a packed `fcc123` raster, using the exact
convention of `spatialrisk.rmj.deforrate`:

```
ndefor_obs = (defor  == 1)                  #  ≡ fcc==1 (cal) / fcc==2 (val)
nfor_obs   = (forest == 1) | (defor == 1)   #  ≡ fcc>0  (cal) / fcc>1  (val)
```

The `(forest == 1) | (defor == 1)` union recovers *forest-at-start* whether the
forest layer encodes the start or end of the period. The predicted half
(risk-category counts × `defor_dens` × `time_interval`), the coarse-grid
partition, the wRMSE/MedAE/RMSE/R² math, and the pred-vs-obs scatter are carried
over unchanged, so results match the legacy/deforisk pipeline exactly.

## 3. Select predictions to evaluate

List every registered prediction and filter it down. Each `Prediction` already
carries everything we need — `dataset_name` (the period), `path` (the risk map),
`model_key`, and `window` — so the two binary layers are recovered from its
dataset, not from disk conventions.

Edit the three knobs below:
* **`DATASETS_TO_EVAL`** — which used-dataset/periods to score (the primary filter).
* **`MODEL_KEYS`** — `None` for all models, or an explicit allow-list.
* **`WINDOWS`** — `None` for all MW windows, or e.g. `[11]` to keep one.

In [5]:
# Map a model_key + window to a short display label
FAMILY = {"glm": "GLM", "rf": "RF", "icar": "ICAR", "mw": "MW", "jnr": "JNR"}
FOREST_VAR = "forest_gfc"   # dataset feature used as 'forest at period start'


def resolve_layers(pred):
    # Recover the two binary layers + time interval from the prediction's dataset
    ds = project.get_dataset(pred.dataset_name)
    if ds is None:
        raise ValueError(f"Dataset '{pred.dataset_name}' not found for {pred.storage_key()}")
    forest = next((f for f in ds.features if f.name == FOREST_VAR), None)
    if forest is None:
        raise ValueError(
            f"Feature '{FOREST_VAR}' not in dataset '{ds.name}'. "
            f"Available: {[f.name for f in ds.features]}"
        )
    return {
        "defor_file": ds.target.path,             # deforestation in the period
        "forest_file": forest.path,               # forest at period start
        "riskmap_file": pred.path,                # categorical risk map
        "time_interval": interval_from_target(ds.target.name),
        "period": pred.dataset_name,
    }

In [6]:
# --- selection knobs ---
DATASETS_TO_EVAL = ["calibration", "validation"]   # filter by used dataset
MODEL_KEYS = None                                  # None = all; or e.g. ["glm_glm_v1", "jnr_calibration_jnr"]
WINDOWS = None                                     # None = all; or e.g. [11]


def select_predictions():
    selected = {}
    for key, pred in project.predictions.items():
        if DATASETS_TO_EVAL and pred.dataset_name not in DATASETS_TO_EVAL:
            continue
        if MODEL_KEYS and pred.model_key not in MODEL_KEYS:
            continue
        if WINDOWS is not None and pred.window is not None and pred.window not in WINDOWS:
            continue
        selected[key] = pred
    return selected


selected = select_predictions()

overview = pd.DataFrame([
    {
        "key": k,
        "label": label_for(p),
        "period": p.dataset_name,
        "time_interval": interval_from_target(project.get_dataset(p.dataset_name).target.name),
        "riskmap": Path(p.path).name,
    }
    for k, p in selected.items()
])
print(f"{len(selected)} prediction(s) selected")
overview

14 prediction(s) selected

,key,label,period,time_interval,riskmap
0,glm_glm_v1__calibration_y2015,GLM,calibration,5,calibration.tif
1,glm_glm_v1__validation_y2015,GLM,validation,4,validation.tif
2,rf_rf_v1__calibration_y2015,RF,calibration,5,calibration.tif
3,rf_rf_v1__validation_y2015,RF,validation,4,validation.tif
4,icar_icar_v1__calibration_y2015,ICAR,calibration,5,calibration.tif
5,icar_icar_v1__validation_y2015,ICAR,validation,4,validation.tif
6,mw_calibration_mw__calibration_y2015_w5,MW_w5,calibration,5,prob_mw_5_calibration.tif
7,mw_calibration_mw__calibration_y2015_w11,MW_w11,calibration,5,prob_mw_11_calibration.tif
8,mw_calibration_mw__calibration_y2015_w21,MW_w21,calibration,5,prob_mw_21_calibration.tif
9,mw_calibration_mw__validation_y2015_w5,MW_w5,validation,4,prob_mw_5_validation.tif
10,mw_calibration_mw__validation_y2015_w11,MW_w11,validation,4,prob_mw_11_validation.tif
11,mw_calibration_mw__validation_y2015_w21,MW_w21,validation,4,prob_mw_21_validation.tif
12,jnr_calibration_jnr__calibration_y2015,JNR,calibration,5,prob_bm_calibration.tif
13,jnr_calibration_jnr__validation_y2015,JNR,validation,4,prob_bm_validation.tif

## 4. Run evaluation — defrate + validation

For each selected prediction:
1. **Per-period defrate** via native `rmj.deforrate.defrate_per_cat`
   (binary `defor` + `forest` + the prediction's risk map) → `defrate_cat_{label}_{period}.csv`.
2. **Validation** via `validate_two_layer` for every coarse-grid size → `indices_…` + `pred_obs_…png`.

Outputs land under `<project>/evaluation/{period}/`.

In [7]:
# --- run knobs ---
CSIZES = [300]              # coarse-grid cell sizes (pixels); must be < 10 km on the ground
RECOMPUTE_DEFRATE = True    # recompute defrate even if the CSV already exists

evaluation_folder = project.folders.project_folder / "evaluation"
evaluation_folder.mkdir(parents=True, exist_ok=True)

rows = []
for key, pred in selected.items():
    lay = resolve_layers(pred)
    label, period, ti = label_for(pred), lay["period"], lay["time_interval"]
    period_dir = evaluation_folder / period
    period_dir.mkdir(parents=True, exist_ok=True)

    # 1) per-period defrate (native two-layer, == riskmapjnr)
    defrate_csv = period_dir / f"defrate_cat_{label}_{period}.csv"
    if RECOMPUTE_DEFRATE or not defrate_csv.exists():
        rmj.deforrate.defrate_per_cat(
            defor_file=lay["defor_file"],
            forest_file=lay["forest_file"],
            riskmap_file=lay["riskmap_file"],
            time_interval=ti,
            tab_file_defrate=defrate_csv,
            verbose=False,
        )

    # 2) validation per coarse-grid size
    for csize in CSIZES:
        idx = validate_two_layer(
            defor_file=lay["defor_file"],
            forest_file=lay["forest_file"],
            riskmap_file=lay["riskmap_file"],
            tab_file_defor=defrate_csv,
            time_interval=ti,
            csize_coarse_grid=csize,
            indices_file_pred=period_dir / f"indices_{label}_{period}_{csize}.csv",
            tab_file_pred=period_dir / f"pred_obs_{label}_{period}_{csize}.csv",
            fig_file_pred=period_dir / f"pred_obs_{label}_{period}_{csize}.png",
            model_name=label,
            period=period,
        )
        idx.update({"prediction": key, "model": label, "period": period})
        rows.append(idx)
        print(f"✓ {label:8s} {period:11s} csize={csize:<4d} "
              f"wRMSE={idx['wRMSE']:8.2f}  MedAE={idx['MedAE']:8.2f}  "
              f"R2={idx['R2']:.2f}  n={idx['ncell']}")

✓ GLM      calibration csize=300  wRMSE=   18.67  MedAE=    2.58  R2=0.65  n=26

✓ GLM      validation  csize=300  wRMSE=   15.03  MedAE=    4.34  R2=0.58  n=26

✓ RF       calibration csize=300  wRMSE=   20.50  MedAE=    2.31  R2=0.56  n=26

✓ RF       validation  csize=300  wRMSE=   15.90  MedAE=    3.36  R2=0.55  n=26

✓ ICAR     calibration csize=300  wRMSE=   18.96  MedAE=    1.30  R2=0.60  n=26

✓ ICAR     validation  csize=300  wRMSE=   15.16  MedAE=    4.33  R2=0.55  n=26

✓ MW_w5    calibration csize=300  wRMSE=    3.34  MedAE=    0.37  R2=1.00  n=26

✓ MW_w11   calibration csize=300  wRMSE=    1.42  MedAE=    0.15  R2=1.00  n=26

✓ MW_w21   calibration csize=300  wRMSE=    1.28  MedAE=    0.17  R2=1.00  n=26

✓ MW_w5    validation  csize=300  wRMSE=    7.07  MedAE=    1.54  R2=0.89  n=26

✓ MW_w11   validation  csize=300  wRMSE=    6.77  MedAE=    1.03  R2=0.90  n=26

✓ MW_w21   validation  csize=300  wRMSE=    6.73  MedAE=    1.16  R2=0.91  n=26

✓ JNR      calibration csize=300  wRMSE=   25.53  MedAE=    3.48  R2=0.16  n=26

✓ JNR      validation  csize=300  wRMSE=   20.06  MedAE=    3.27  R2=0.17  n=26

## 5. Aggregate indices

In [8]:
indices_all = pd.DataFrame(rows)[[
    "prediction", "model", "period",
    "csize_coarse_grid", "csize_coarse_grid_ha", "ncell",
    "MedAE", "R2", "RMSE", "wRMSE",
]].sort_values(["csize_coarse_grid", "period", "model"]).reset_index(drop=True)

indices_all.to_csv(evaluation_folder / "indices_all.csv", index=False)
print(f"Saved {evaluation_folder / 'indices_all.csv'}")
indices_all

Saved /home/jserafini/Desktop/projects/spatial_risk/spatial-risk-module/data/mtq-refactor/evaluation/indices_all.csv

,prediction,model,period,csize_coarse_grid,csize_coarse_grid_ha,ncell,MedAE,R2,RMSE,wRMSE
0,glm_glm_v1__calibration_y2015,GLM,calibration,300,8100.0,26,2.58,0.65,15.66,18.67
1,icar_icar_v1__calibration_y2015,ICAR,calibration,300,8100.0,26,1.30,0.60,15.80,18.96
2,jnr_calibration_jnr__calibration_y2015,JNR,calibration,300,8100.0,26,3.48,0.16,21.23,25.53
3,mw_calibration_mw__calibration_y2015_w11,MW_w11,calibration,300,8100.0,26,0.15,1.00,1.18,1.42
4,mw_calibration_mw__calibration_y2015_w21,MW_w21,calibration,300,8100.0,26,0.17,1.00,1.08,1.28
5,mw_calibration_mw__calibration_y2015_w5,MW_w5,calibration,300,8100.0,26,0.37,1.00,2.80,3.34
6,rf_rf_v1__calibration_y2015,RF,calibration,300,8100.0,26,2.31,0.56,17.12,20.50
7,glm_glm_v1__validation_y2015,GLM,validation,300,8100.0,26,4.34,0.58,12.85,15.03
8,icar_icar_v1__validation_y2015,ICAR,validation,300,8100.0,26,4.33,0.55,12.89,15.16
9,jnr_calibration_jnr__validation_y2015,JNR,validation,300,8100.0,26,3.27,0.17,16.99,20.06
10,mw_calibration_mw__validation_y2015_w11,MW_w11,validation,300,8100.0,26,1.03,0.90,5.89,6.77
11,mw_calibration_mw__validation_y2015_w21,MW_w21,validation,300,8100.0,26,1.16,0.91,5.87,6.73
12,mw_calibration_mw__validation_y2015_w5,MW_w5,validation,300,8100.0,26,1.54,0.89,6.10,7.07
13,rf_rf_v1__validation_y2015,RF,validation,300,8100.0,26,3.36,0.55,13.53,15.90

## 6. Visual comparison

Grouped bar charts of each accuracy index by model × period (the new-construction
analog of the probability-map grid in `6.all_models_benchmark`). Lower wRMSE /
MedAE / RMSE is better; higher R² is better.

In [9]:
metrics = ["wRMSE", "MedAE", "RMSE", "R2"]
csize_plot = CSIZES[0]
d = indices_all[indices_all["csize_coarse_grid"] == csize_plot]

models = sorted(d["model"].unique())
periods = [p for p in ["calibration", "validation"] if p in set(d["period"])]
xpos = np.arange(len(models))
width = 0.8 / max(1, len(periods))

fig, axes = plt.subplots(2, 2, figsize=(14, 9))
for ax, metric in zip(axes.ravel(), metrics):
    for i, per in enumerate(periods):
        vals = [
            d[(d["model"] == m) & (d["period"] == per)][metric].mean()
            for m in models
        ]
        ax.bar(xpos + (i - (len(periods) - 1) / 2) * width, vals, width, label=per)
    ax.set_xticks(xpos)
    ax.set_xticklabels(models, rotation=45, ha="right")
    ax.set_title(metric + ("  (ha)" if metric != "R2" else ""))
    ax.grid(axis="y", linestyle=":", alpha=0.5)
    ax.legend(title="period")

fig.suptitle(
    f"Model validation indices — {project_name} (coarse grid = {csize_plot} px)",
    fontsize=14,
)
plt.tight_layout()
plt.show()

/tmp/ipykernel_2812484/1338222911.py:29: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()